### ISSUE TITLE
误报率有点高

### ISSUE THREAD

**Issue by TryA9ain** [pmiaowu/BurpShiroPassiveScan#18]
![image](https://user-images.githubusercontent.com/51145610/147544250-de711d27-2fc5-4493-9964-ecf4fc4f6b72.png)

使用市面的大部分工具都检测不出来

![image](https://user-images.githubusercontent.com/51145610/147548927-03c1e6e2-cef4-4d37-8cde-1a2d7e8e67c0.png)

**Comment by pmiaowu** [comment]
你的站点是啥?可以发我看看么?一般来说,漏报还有可能,误报应该只有极端情况才有可能,你看看你的数据包
数据包构造的不同,对于那种直接利用的工具,是可能会检测不出来的
