### ISSUE TITLE
UTF-8编码显示乱码

### ISSUE THREAD

**Issue by TryA9ain** [pmiaowu/BurpShiroPassiveScan#2]
换成别的编码就不乱码，但是request 和 response 中文又会乱码，这就很烦~~~~~~
![image](https://user-images.githubusercontent.com/51145610/91052475-190ac900-e654-11ea-95a4-517ad9a23f31.png)
![image](https://user-images.githubusercontent.com/51145610/91052675-5ec79180-e654-11ea-932a-f35d2ccb06b5.png)
![image](https://user-images.githubusercontent.com/51145610/91052734-743cbb80-e654-11ea-8746-7f3ae0e1ab09.png)

**Comment by pmiaowu** [comment]
请问一下，您的burp版本是？如果是过于低的burp版本
中文乱码问题在burp低版本得起是个挺要命的情况，我也无法很好的解决。
如果是高于1.7的话，那就可以通过burp的设置来解决中文编码与乱码的问题
