### ISSUE TITLE
一个小建议

### ISSUE THREAD

**Issue by xiaozhaha** [pmiaowu/BurpShiroPassiveScan#21]
师傅可以把夏天师傅的shiro工具的key加入吗？
https://github.com/SummerSec/ShiroAttack2
我尝试过自己编译，但是加载到bp没有用，不跑key。
谢谢师傅写出这么舒服的工具。

**Comment by pmiaowu** [comment]
啊,不想加,太多key,burp的被动扫描器自己顶不住
