### ISSUE TITLE
key扫描完需要多长时间

### ISSUE THREAD

**Issue by linuxdy** [pmiaowu/BurpShiroPassiveScan#23]
1.自己增加key到1300左右，发现burp扫描key20分钟左右都没扫完
<img width="1147" alt="image" src="https://user-images.githubusercontent.com/50064309/158768886-c55b1758-09c1-4f74-84bd-081779c99e2e.png">

**Comment by pmiaowu** [comment]
没计算过,看站点处理速度把
每个请求都是单线程的,不建议加这么多key,因为acg与gcm你这样要跑2600个请求,对单线程压力很大的.
而且经我对实战来说,能遇到的还是kp那几个key多那么多key没有什么意义=-=
