### ISSUE TITLE
插件新版不能用

### ISSUE THREAD

**Issue by hunter-00** [pmiaowu/BurpShiroPassiveScan#24]
![image](https://user-images.githubusercontent.com/67944000/165702780-0f42239e-af04-47a2-aed3-fc7e3960b62d.png)
![image](https://user-images.githubusercontent.com/67944000/165702831-5f54f1e0-d9cd-4e32-94d5-05cc77094a2a.png)

**Comment by BambooLove** [comment]
你被动扫描开了吗？
