### ISSUE TITLE
java版本与GCM加密问题

### ISSUE THREAD

**Issue by S9MF** [pmiaowu/BurpShiroPassiveScan#26]
站点存在shiro漏洞，gcm加密

使用java1.8 启动的burp加载，插件扫出key
![java8](https://user-images.githubusercontent.com/48114638/170040040-0a440d9c-7779-4932-aef2-7e27e3755d0e.jpg)

使用java14 启动的burp加载，插件没扫出key
![java14](https://user-images.githubusercontent.com/48114638/170040285-65a4dc86-bed0-45a1-ba6f-da35622bd9b3.jpg)
看来下日志gcm加密检测key时，rememberme=0

这里我修改了下插件代码，解决问题
![gcm](https://user-images.githubusercontent.com/48114638/170040765-19676c5f-9608-43df-b955-0a1a4c576dc9.jpg)

**Comment by pmiaowu** [comment]
感谢提交,晚点我测试一下对其它java版本是否有影响,如果没影响我就更新一下
