### ISSUE TITLE
可否将标签中的NAME更改短一些，这样子在burp的视图里面就不会占太多位置了

### ISSUE THREAD

**Issue by ym2011** [pmiaowu/BurpShiroPassiveScan#3]
可否将标签中的NAME更改短一些，这样子在burp的视图里面就不会占太多位置了
标签界面：
   public static String NAME = "ShiroScan";

**Comment by pmiaowu** [comment]
行，满足你，现在就更新

**Comment by pmiaowu** [comment]
行，满足你，现在就更新
