### ISSUE TITLE
大佬你好，插件貌似没有流量进去

### ISSUE THREAD

**Issue by L3B1anc** [pmiaowu/BurpShiroPassiveScan#30]
现在用2022版本的burp扫不出来东西，被动扫描默认开启的，你的其他log4j和fastjson插件都有数据，但是shiro里面是空的。
<img width="1372" alt="image" src="https://user-images.githubusercontent.com/30144475/181673180-02df6862-5e8a-48e4-8c73-c36f02fd74c4.png">
<img width="850" alt="image" src="https://user-images.githubusercontent.com/30144475/181673206-bc1af5a1-7e4f-4ad9-bbf3-705f5da4e7da.png">

**Comment by L3B1anc** [comment]
mac电脑，版本是最新版的burp，同事测试2022.5也不行

**Comment by pmiaowu** [comment]
如果是确定这个站点有shiro的话,你可以打开: ./resources/config.yml
找到suffixList,可能是因为这个后缀黑名单影响到了

**Comment by L3B1anc** [comment]
应该不是这个问题，标签里面就一直是空的，没有URL，感觉就是没有开始扫描
