### ISSUE TITLE
请教这里是不是有一个小问题

### ISSUE THREAD

**Issue by xunyang1** [pmiaowu/BurpShiroPassiveScan#31]
最近在学习师傅的插件，有一处存在疑惑
这个地方填入的是默认固定值，不应该是从请求中获取吗
![image](https://user-images.githubusercontent.com/78201553/191031881-a69671c0-b3e3-4626-97c0-22d6b55a2748.png)

这里我采用ShiroFingerprint3扩展检测
rememberMe=aaa
![image](https://user-images.githubusercontent.com/78201553/191030614-18acf3da-36d6-4307-955b-fe0efd90e9f7.png)
而插件显示该请求的rememberMe=3
![image](https://user-images.githubusercontent.com/78201553/191031473-72c47824-49c1-45cc-bfed-6bcfaa99a2f2.png)
![image](https://user-images.githubusercontent.com/78201553/191031520-7b2a29e1-0ff9-4d6b-ad27-5ea0fc762526.png)

**Comment by pmiaowu** [comment]
不好意思,最近邮件太多,没看到
这里是这样的src/main/java/burp/Application/ShiroFingerprintExtension/ExtensionMethod/ShiroFingerprint3.java
这个文件的是写死rememberMe的value哦
你在ShiroFingerprint3.java 搜索 private String rememberMeCookieValue = "3"; 就可以看到
