### ISSUE TITLE
能不能加一个textbox，用来自定义加密key

### ISSUE THREAD

**Issue by 0xn0ne** [pmiaowu/BurpShiroPassiveScan#6]
RT

**Comment by pmiaowu** [comment]
我最近在考虑要不要把key这一部分独立到一个txt文件中,到时候就可以自己修改那个txt来自定义加密key了

**Comment by pmiaowu** [comment]
至于加一个 textbox 感觉还不如搞成一个txt永久保存的好，不然burp一关 textbox 的数据就没了QAQ

**Comment by 0xn0ne** [comment]
> 至于加一个 textbox 感觉还不如搞成一个txt永久保存的好，不然burp一关 textbox 的数据就没了QAQ

嘿嘿嘿，对，都行，祝大佬新年新气象
