### ISSUE TITLE
要求版本是多少我的java是1.8

### ISSUE THREAD

**Issue by komomon** [pmiaowu/BurpShiroPassiveScan#9]

**Comment by komomon** [comment]
> _No description provided._
java1.8 burp 2.0.11 安装报错

**Comment by pmiaowu** [comment]
我编译使用的是java1.8，如果是高于burp2.0的安装的话，需要使用你burp的那个版本重新编译一下源码。
例如你这个2.0使用的是java11，那么就要使用java11重新编译
